---
 
- name: Config Nginx
  hosts: server
  tasks:

    - name: Config nginx déplace les fichier dans mastodon  
      copy:
        src: /home/mastodon/live/dist/nginx.conf 
        dest: /etc/nginx/sites-available/mastodon
        remote_src: true

    - name: Creating a symlink
      ansible.builtin.file:
        src: /etc/nginx/sites-available/mastodon 
        dest: /etc/nginx/sites-enabled/mastodon
        state: link


    - name:  send key and certificate
      copy:
        src: ../{{ item }}
        dest: /etc/ssl/{{ item }}
        mode: 0400
      with_items:
      - "mastodon.com.key"
      - "mastodon.com.pem"
      become: true



      #server http
    - name: Add a line server_name Keyce to a file mastodon
      ansible.builtin.lineinfile:
        path: /etc/nginx/sites-available/mastodon
        regexp: '\s\sserver_name\sexample.com;'
        line: '  server_name {{dns_server}}'
        state: present

      #server https
    - name: Add a line server_name Keyce to a file mastodon
      ansible.builtin.lineinfile:
        path: /etc/nginx/sites-available/mastodon
        regexp: '\s\sserver_name\sexample.com;'
        line: '  server_name {{dns_server}}'
        state: present
        

    - name: Add a line server_name Keyce to a file mastodon
      ansible.builtin.lineinfile:
        path: /etc/nginx/sites-available/mastodon
        insertafter: '(^|)ssl_certificate_key(|$)'
        firstmatch: yes
        line: '  ssl_certificate /etc/ssl/{{ dns_server }}.pem;'
        state: present

    - name: Add a line server_name Keyce to a file mastodon
      ansible.builtin.lineinfile:
        path: /etc/nginx/sites-available/mastodon
        insertafter: '(^|)ssl_certificate_key(|$)'
        firstmatch: yes
        line: '  ssl_certificate_key /etc/ssl/{{ dns_server }}.key;'
        state: present

    - name: restart nginx
      ansible.builtin.systemd:
        state: restarted
        name: nginx

    - name: Install core
      community.general.snap:
        name:
          - core

    - name: Update snap package
      command: snap refresh core

    - name: Install certbot via snap.
      snap:
        name: certbot
        classic: true

    - name: copy file mastodon streaming to systemd system
      copy:
        src: /home/mastodon/live/dist/mastodon-streaming.service
        dest: /etc/systemd/system/
        remote_src: true

    - name: copy file mastodon sidekiq to systemd
      copy:
        src: /home/mastodon/live/dist/mastodon-sidekiq.service
        dest: /etc/systemd/system/
        remote_src: true  


    - name: copy file mastodon web service to systemd
      copy:
        src: /home/mastodon/live/dist/mastodon-web.service
        dest: /etc/systemd/system/
        remote_src: true


      #Relan
    - name: reload systemd
      command: systemctl daemon-reload
      # Démarrer les nouveaux services systemd: service web/sidekiq/streaming
    - name: start mastodon web service
      ansible.builtin.systemd:
        state: started
        name: mastodon-web.service

    - name: start mastodon sidekiq.service
      ansible.builtin.systemd:
        state: started
        name: mastodon-sidekiq.service

    - name: start mastodon streaming.service
      ansible.builtin.systemd:
        state: started
        name: mastodon-streaming.service


    - name: Restart Mastodon Sidekiq
      systemd:
        name: mastodon-sidekiq
        state: restarted

    - name: Reload Mastodon Web
      systemd:
        name: mastodon-web
        state: reloaded